;****** Include Files ******
.include "m8535def.inc"


;****** Initialize GPR ******
.def TEMPR1 = R16
.def TEMPR2 = R17
.def TEMPR3 = R18
.def DELAY_PARAM = R19


;****** Initialize CONST ******

;*** PORT/PIN ***
.equ SOUNDER = (1<<PORTD5)

;*** Timer 1 Parameters ***
.equ TIM1_PSC_RESET = (1<<CS12)|(1<<CS11)|(1<<CS10)
.equ TIM1_PSC64 = (0<<CS12)|(1<<CS11)|(1<<CS10)
.equ TIM1_MODE_RESET_A = (1<<WGM11)|(1<<WGM10)
.equ TIM1_MODE_RESET_B = (1<<WGM13)|(1<<WGM12)
.equ TIM1_FAST_PWM_OCR1A_A = (1<<WGM11)|(1<<WGM10)
.equ TIM1_FAST_PWM_OCR1A_B = (1<<WGM13)|(1<<WGM12)
.equ TIM1_COM_RESET_A = (1<<COM1A1)|(1<<COM1A0)
.equ TIM1_FAST_PWM_TOGGLE_OC1A = (0<<COM1A1)|(1<<COM1A0)
;.equ TIM1_INT_OVF_EN = (1<<TOIE1)

;*** Timer 0 Parameters ***
.equ TIM0_PSC_RESET = (1<<CS02)|(1<<CS01)|(1<<CS00)
.equ TIM0_PSC256 = (1<<CS12)|(0<<CS11)|(0<<CS10)
.equ TIM0_MODE_RESET = (1<<WGM01)|(1<<WGM00)
.equ TIM0_NORMAL_MODE = (0<<WGM01)|(0<<WGM00)
.equ TIM0_COM_RESET = (1<<COM01)|(1<<COM00)
.equ TIM0_COM_DISCONNECT = (0<<COM01)|(0<<COM00)
.equ TIM0_INT_OVF_EN = (1<<TOIE0)

;*** Musical Notes ***
;** 1st Octava **
.equ C4 = 0x1E;	(CLK=1MHz)/64 = 2*(C4=30) * 262 Hz
.equ C4D4 = 0x1C;	(CLK=1MHz)/64 = 2*(C4D4=28) * 277 Hz
.equ D4 = 0x1B;	(CLK=1MHz)/64 = 2*(D4=27) * 294 Hz
.equ D4E4 = 0x19;	(CLK=1MHz)/64 = 2*(D4E4=25) * 311 Hz
.equ E4 = 0x18;	(CLK=1MHz)/64 = 2*(E4=24) * 330 Hz
.equ F4 = 0x16;	(CLK=1MHz)/64 = 2*(F4=22) * 349 Hz
.equ F4G4 = 0x15;	(CLK=1MHz)/64 = 2*(F4G4=21) * 370 Hz
.equ G4 = 0x14;	(CLK=1MHz)/64 = 2*(G4=20) * 392 Hz
.equ G4A4 = 0x13;	(CLK=1MHz)/64 = 2*(G4A4=19) * 415 Hz
.equ A4 = 0x12;	(CLK=1MHz)/64 = 2*(A4=18) * 440 Hz
.equ A4B4 = 0x11;	(CLK=1MHz)/64 = 2*(A4B4=17) * 466 Hz
.equ B4 = 0x10;	(CLK=1MHz)/64 = 2*(B4=16) * 494 Hz
;** 2nd Octava **
.equ C5 = 0x0F;	(CLK=1MHz)/64 = 2*(C5=15) * 523 Hz
.equ C5D5 = 0x0E;	(CLK=1MHz)/64 = 2*(C5D5=14) * 554 Hz
.equ D5 = 0x0D;	(CLK=1MHz)/64 = 2*(B4=13) * 587 Hz

;****** Interrup Vector ******
.org 0x0
	RJMP RESET
	RETI;	RJMP EXT_INT0
	RETI;	RJMP EXT_INT1
	RETI;	RJMP TIM2_COMP
	RETI;	RJMP TIM2_OVF
	RETI;	RJMP TIM1_CAPT
	RETI;	RJMP TIM1_COMPA
	RETI;	RJMP TIM1_COMPB
	RETI;	RJMP TIM1_OVF
	RJMP TIM0_OVF
	RETI;	RJMP SPI_STC
	RETI;	RJMP USART_RXC
	RETI;	RJMP USART_DRE
	RETI;	RJMP USART_TXC
	RETI;	RJMP ADC_COMP
	RETI;	RJMP EE_READY
	RETI;	RJMP ANA_COMP
	RETI;	RJMP TWI
	RETI;	RJMP INT2
	RETI;	RJMP TIM0_COMP
	RETI;	RJMP SPM_RDY

.org 0x15
	RESET:
		;	Initialize Stack
		LDI TEMPR1, LOW(RAMEND)
		OUT SPL, TEMPR1
		LDI TEMPR1, HIGH(RAMEND)
		OUT SPH, TEMPR1

		;	Initialize PORTD5(OC1A Pin) As Output For Sounder
		IN TEMPR1, DDRD
		SBR TEMPR1, SOUNDER
		OUT DDRD, TEMPR1

		;*** Timer 1 Settings ***
		;	Select Clock Source With Prescaler 1024, i.e. Frequency/1024
		IN TEMPR1, TCCR1B
		CBR TEMPR1, TIM1_PSC_RESET
		SBR TEMPR1, TIM1_PSC64
		OUT TCCR1B, TEMPR1
		;	Enable Fast PWM OCR1A Mode
		IN TEMPR1, TCCR1B
		CBR TEMPR1, TIM1_MODE_RESET_B
		SBR TEMPR1, TIM1_FAST_PWM_OCR1A_B
		OUT TCCR1B, TEMPR1
		IN TEMPR1, TCCR1A
		CBR TEMPR1, TIM1_MODE_RESET_A
		SBR TEMPR1, TIM1_FAST_PWM_OCR1A_A
		OUT TCCR1A, TEMPR1
		;	Select Fast PWM Mode, Toggle OC1A Pin On Compare Match
		IN TEMPR1, TCCR1A
		CBR TEMPR1, TIM1_COM_RESET_A
		SBR TEMPR1, TIM1_FAST_PWM_TOGGLE_OC1A
		OUT TCCR1A, TEMPR1
;		;	Enable Overflow Interrupt
;		IN TEMPR1, TIMSK
;		SBR TEMPR1, TIM1_INT_OVF
;		OUT TIMSK, TEMPR1

		;*** Timer 0 Settings ***
		IN TEMPR1, TCCR0
		;	Reset Clock Source To None, Timer0 Turned Off
		CBR TEMPR1, TIM0_PSC_RESET
		SBR TEMPR1, TIM0_PSC256
		;	Enable Normal Mode
		CBR TEMPR1, TIM0_MODE_RESET
		SBR TEMPR1, TIM0_NORMAL_MODE
		;	Disconnect OC0 For Normal Port Operation
		CBR TEMPR1, TIM0_COM_RESET
		SBR TEMPR1, TIM0_COM_DISCONNECT
		OUT TCCR0, TEMPR1
		;	Enable Overflow Interrupt
		IN TEMPR1, TIMSK
		SBR TEMPR1, TIM0_INT_OVF_EN
		OUT TIMSK, TEMPR1

		;	Enable Global Interrupt
		SEI


;****** Main Program ******
	LOOP:
;		RCALL CHRISTMAS_TREE_BORN
;		RCALL HAPPY_BIRHTDAY
;		RCALL GRASSHOPPER
;		RCALL TWO_GEESE
;		RCALL GOOD_NIGHT_BABY
;		RCALL SMILE
;		RCALL CHUNGA_CHANGA
;		RCALL LITTLE_CHRISTMAS_TREE
;		RCALL JINGLE_BELLS		
		RJMP LOOP;	Start LOOP Again

;****** SubPrograms ******

	;*** Play Musical Note As Pressed Piano Key ***
	PLAY_MUSICAL_NOTE:
		OUT OCR1AL, TEMPR1
		LDI TEMPR1, 0x00
		OUT TCNT1H, TEMPR1
		OUT TCNT1L, TEMPR1		
		IN TEMPR1, TCCR0
		SBR TEMPR1, TIM0_PSC256
		OUT TCCR0, TEMPR1
		MOV TEMPR1, DELAY_PARAM
		PLAY_MUSICAL_NOTE_LOOP:
			CPI TEMPR1, 0
			BRNE PLAY_MUSICAL_NOTE_LOOP
		IN TEMPR1, TCCR0
		CBR TEMPR1, TIM0_PSC_RESET
		OUT TCCR0, TEMPR1	
		RET;	SubProgram Return

	;*** Delay ***
	DELAY:
		;	Select Clock Source For Timer0 To Start Counting
		IN TEMPR1, TCCR0
		SBR TEMPR1, TIM0_PSC256
		OUT TCCR0, TEMPR1
		MOV TEMPR1, DELAY_PARAM
		ONE_SEC_DELAY_LOOP:
			CPI TEMPR1, 0
			BRNE ONE_SEC_DELAY_LOOP
		;	Reset Clock Source To None, Timer0 Turned Of
		IN TEMPR1, TCCR0
		CBR TEMPR1, TIM0_PSC_RESET
		OUT TCCR0, TEMPR1	
		RET;	SubProgram Return

	;*** Success Beep Sound ***
	SUCCESS_BEEP:
		LDI DELAY_PARAM, 2
		LDI TEMPR1, 7
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 3
		LDI TEMPR1, 5
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 4
		LDI TEMPR1, 3
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 8
		LDI TEMPR1, 2
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 3
		LDI TEMPR1, 5
		RCALL PLAY_MUSICAL_NOTE
		RET;	SubProgram Return

	;*** Error Beep Sound ***
	ERROR_BEEP:
		LDI DELAY_PARAM, 9
		LDI TEMPR1, 172
		RCALL PLAY_MUSICAL_NOTE
		RET;	SubProgram Return

	;*** Error Beep Sound ***
	BEEP:
		LDI DELAY_PARAM, 9
		LDI TEMPR1, 210
		RCALL PLAY_MUSICAL_NOTE
		RET;	SubProgram Return

	;*** В Лесу Родилась Ёлочка ***
	CHRISTMAS_TREE_BORN:
		LDI DELAY_PARAM, 4
		;1st Verse: В Лесу Родилась Ёлочка
		RCALL CHRISTMAS_TREE_BORN_REPEATED_VERSE
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		;2nd Verse: В Лесу Она Росла
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4B4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, D5
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, C5
		RCALL PLAY_MUSICAL_NOTE
		;3rd Verse: Зимой И Летом Стройная
		LDI TEMPR1, C5
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, D4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, D4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4B4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4B4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		;4th Verse: Зеленая Была
		RCALL CHRISTMAS_TREE_BORN_REPEATED_VERSE
		RET;	SubProgram Return
	;	CHRISTMAS_TREE_BORN_REPEATED_VERSE
	CHRISTMAS_TREE_BORN_REPEATED_VERSE:
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE	
		RET;	SubProgram Return

	;*** Happy Birthday To You ***
	HAPPY_BIRHTDAY:
		LDI DELAY_PARAM, 6
		;1st Verse: Happy Birthday To You
		RCALL HAPPY_BIRHTDAY_REPEATED_VERSE
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 6
		;2nd Verse: Happy Birthday To You
		LDI TEMPR1, C4
		RCALL HAPPY_BIRHTDAY_REPEATED_VERSE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 6
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 6
		;3rd Verse: Happy Birthday Dear ...
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, D4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 6
		;4th Verse: Happy Birthday To You
		LDI TEMPR1, A4B4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4B4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 6
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 6
		RET;	SubProgram Return		
	;	HAPPY_BIRHTDAY_REPEATED_VERSE
	HAPPY_BIRHTDAY_REPEATED_VERSE:
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, D4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 6
		RET;	SubProgram Return

	;*** В Траве Сидел Кузнечик ***
	GRASSHOPPER:
		LDI DELAY_PARAM, 4
		;1st Verse: В Траве Сидел Кузнечик
		LDI TEMPR2, 2
		REPEAT_LOOP3:
			LDI TEMPR1, F4
			RCALL PLAY_MUSICAL_NOTE
			LDI TEMPR1, C4
			RCALL PLAY_MUSICAL_NOTE
			LDI DELAY_PARAM, 1
			RCALL DELAY
			LDI DELAY_PARAM, 4
			DEC TEMPR2
			BRNE REPEAT_LOOP3
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		;2nd Verse: В Траве Сидел Кузнечик
		LDI TEMPR2, 2
		REPEAT_LOOP4:
			LDI TEMPR1, E4
			RCALL PLAY_MUSICAL_NOTE
			LDI TEMPR1, C4
			RCALL PLAY_MUSICAL_NOTE
			LDI DELAY_PARAM, 1
			RCALL DELAY
			LDI DELAY_PARAM, 4
			DEC TEMPR2
			BRNE REPEAT_LOOP4
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		;3rd Verse: Совсем Как Огуречик
		LDI TEMPR2, 2
		REPEAT_LOOP5:
			LDI TEMPR1, F4
			RCALL PLAY_MUSICAL_NOTE
			LDI TEMPR1, C4
			RCALL PLAY_MUSICAL_NOTE
			LDI DELAY_PARAM, 1
			RCALL DELAY
			LDI DELAY_PARAM, 4
			DEC TEMPR2
			BRNE REPEAT_LOOP5
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		;4th Verse: Зелёненький Он Был
		LDI TEMPR2, 2
		REPEAT_LOOP6:
			LDI TEMPR1, E4
			RCALL PLAY_MUSICAL_NOTE
			LDI TEMPR1, C4
			RCALL PLAY_MUSICAL_NOTE
			DEC TEMPR2
			BRNE REPEAT_LOOP6
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 4
		RCALL DELAY
		LDI DELAY_PARAM, 4
		;	2nd Part
		LDI TEMPR2, 2
		REPEAT_LOOP:
			LDI DELAY_PARAM, 3
			;5th Verse: Представьте Себе, Представьте Себе
			LDI TEMPR1, F4
			RCALL PLAY_MUSICAL_NOTE
			LDI TEMPR3, 5
			REPEAT_LOOP1:
				LDI TEMPR1, G4
				RCALL PLAY_MUSICAL_NOTE
				DEC TEMPR3
				BRNE REPEAT_LOOP1
			LDI TEMPR3, 4
			REPEAT_LOOP2:
				LDI TEMPR1, G4A4
				RCALL PLAY_MUSICAL_NOTE
				DEC TEMPR3
				BRNE REPEAT_LOOP2
			LDI DELAY_PARAM, 4
			;6th Verse: Совсем Как Огуречик
			LDI TEMPR1, G4A4
			RCALL PLAY_MUSICAL_NOTE
			LDI TEMPR1, G4A4
			RCALL PLAY_MUSICAL_NOTE
			LDI TEMPR1, G4
			RCALL PLAY_MUSICAL_NOTE
			LDI TEMPR1, F4
			RCALL PLAY_MUSICAL_NOTE
			LDI TEMPR1, E4
			RCALL PLAY_MUSICAL_NOTE
			LDI TEMPR1, F4
			RCALL PLAY_MUSICAL_NOTE
			LDI TEMPR1, F4
			RCALL PLAY_MUSICAL_NOTE
			DEC TEMPR2
			BRNE REPEAT_LOOP
		RET;	SubProgram Return

	;*** Жили У Бабуси Два Веселых Гуся ***
	TWO_GEESE:
		LDI DELAY_PARAM, 4
		;1st Verse: Жили У Бабуси Два Веселых Гуся
		LDI TEMPR2, 2
		TWO_GEESE_FIRST_LOOP:
			RCALL TWO_GEESE_REPEATED_VERSE
			LDI TEMPR1, A4
			RCALL PLAY_MUSICAL_NOTE
			LDI TEMPR1, A4
			RCALL PLAY_MUSICAL_NOTE
			LDI DELAY_PARAM, 1
			RCALL DELAY
			LDI DELAY_PARAM, 4
			DEC TEMPR2
			BRNE TWO_GEESE_FIRST_LOOP
		;2nd Verse: Один Серый Другой Белый
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 4
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 4
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		;3rd Verse: Два Веселых Гуся
		RCALL TWO_GEESE_REPEATED_VERSE
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		RET;	SubProgram Return
	;	TWO_GEESE_REPEATED_VERSE
	TWO_GEESE_REPEATED_VERSE:
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 4
		LDI TEMPR1, D4
		RCALL PLAY_MUSICAL_NOTE
		RET;	SubProgram Return

	;*** Спят Усталые Игрушки! ***
	GOOD_NIGHT_BABY:
		LDI DELAY_PARAM, 5
		;1st Verse: Спят Усталые Игрушки, Книжки Спят
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 5
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, D4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 5
		;2nd Verse: Одеяло И Подушки Ждут Ребят
		RCALL GOOD_NIGHT_BABY_REPEATED_VERSE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 5
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, D4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, D4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, D4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 5
		;3rd Verse: За День Мы Устали Очень
		LDI DELAY_PARAM, 4
		RCALL GOOD_NIGHT_BABY_REPEATED_VERSE
		LDI DELAY_PARAM, 3
		RCALL DELAY
		LDI DELAY_PARAM, 4
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 4
		;4th Verse: Скажем Всем Спокойной Ночи
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 5
		;5th Verse: Глазки Закрывай
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 5
		;6th Verse: Баю-бай
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 3
		RCALL DELAY
		LDI DELAY_PARAM, 5
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 3
		RCALL DELAY
		LDI DELAY_PARAM, 5
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 4
		RCALL DELAY
		LDI DELAY_PARAM, 5
		RET;	SubProgram Return
	;*** GOOD_NIGHT_BABY_REPEATED_VERSE ***
	GOOD_NIGHT_BABY_REPEATED_VERSE:
		LDI TEMPR1, D4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, D4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		RET;	SubProgram Return

	;*** Улыбка ***
	SMILE:
		LDI DELAY_PARAM, 3
		;	1st Verse
		LDI TEMPR1, G4;	Oт
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4;	У
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4;	лыб
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4; ки 
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, D4;	Хму
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, F4;	pый
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, E4;	День
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, D4;	Свет
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, C4;	лей
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		;	2nd Verse
		LDI TEMPR1, E4;	Oт
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4;	У
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4;	лыб
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, A4;	ки
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, A4;	В Не
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, B4;	бе
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, D5;	Ра
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, C5;	ду
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, B4;	га
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, A4;	Пpo
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, C5;	cнет
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4;	cя
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		;	3rd Verse
		LDI TEMPR1, A4;	Пo	
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, B4;	де
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, C5;	лиcь	
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, B4;	У
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4;	лыб
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, E4;	кo
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4;	ю
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, F4;	Свo
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, A4;	ей
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		;	4th Verse
		LDI TEMPR1, B4;	И
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4;	О
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, C5;	на
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4;	К Те
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, B4;	бе
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, A4;	Не
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, A4;	Раз
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4;	Е
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, D4;	ще
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, E4;	Веp
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, D4;	нет
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, C4;	cя
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		RET;	SubProgram Return

	;*** Чунга-чанга ***
	CHUNGA_CHANGA:
		LDI DELAY_PARAM, 3
		;	1st Verse
		RCALL CHUNGA_CHANGA_REPEATED_VERSE1
		LDI TEMPR1, G4;	Си
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, F4;	ний
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4;	Не
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4A4; бо
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4;	вод
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		;	2nd Verse
		RCALL CHUNGA_CHANGA_REPEATED_VERSE2
		LDI TEMPR1, D4;	Ле
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, D4E4; то
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, F4;	Круг
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4; лый
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, D4E4; Год
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		;	3rd Verse
		RCALL CHUNGA_CHANGA_REPEATED_VERSE1
		LDI TEMPR1, G4;	Ве
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, F4;	се
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, G4;	ло
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4A4; Жи
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4;	вем
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		;	4th Verse
		RCALL CHUNGA_CHANGA_REPEATED_VERSE2
		LDI TEMPR1, D4;	Пе
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, D4E4; сен
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, F4;	ку
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4; По
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, D4E4; ем
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		RET;	SubProgram Return
	;*** CHUNGA_CHANGA_REPEATED_VERSE1 ***
	CHUNGA_CHANGA_REPEATED_VERSE1:
		LDI TEMPR1, C4;	Чун
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, D4E4; га
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4;	Чан
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4;	га
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		RET;	SubProgram Return
	;*** CHUNGA_CHANGA_REPEATED_VERSE2 ***
	CHUNGA_CHANGA_REPEATED_VERSE2:
		LDI TEMPR1, C5;	Чун
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, D4E4; га
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, D4;	Чан
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, D4;	га
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		RET;	SubProgram Return

	;*** Маленькой Ёлочке Холодно Зимой ***
	LITTLE_CHRISTMAS_TREE:
		LDI DELAY_PARAM, 3
		;	1st Verse
		LDI TEMPR1, G4;	Ма
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, E4; лень
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, E4;	кой
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4;	Ё
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4;	лоч
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, E4;	ке
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		;	2nd Verse: Хо-лод-но Зи-мой
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		RCALL LITTLE_CHRISTMAS_TREE_REPEATED_VERSE
		;	3rd Verse
		LDI TEMPR1, B4;	Из
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, C5;	Ле
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, B4;	су
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4; Ё
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, E4;	лоч
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, E4; ку
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		;	4th Verse: Взя-ли Мы До-мой
		LDI TEMPR1, G4 
		RCALL PLAY_MUSICAL_NOTE
		RCALL LITTLE_CHRISTMAS_TREE_REPEATED_VERSE
		RET;	SubProgram Return
	;*** LITTLE_CHRISTMAS_TREE_REPEATED_VERSE ***
	LITTLE_CHRISTMAS_TREE_REPEATED_VERSE:
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, D4	
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		RET;	SubProgram Return

	;*** Jingle Bells ***
	JINGLE_BELLS:
		LDI DELAY_PARAM, 3
		;	1st Verse
		RCALL JINGLE_BELLS_FIRST_VERSE
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		;	2nd Verse
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		RCALL JINGLE_BELLS_SECOND_VERSE
		LDI TEMPR1, D4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		;	3rd Verse
		RCALL JINGLE_BELLS_THIRD_VERSE
		LDI TEMPR1, E4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		;	4th Verse
		LDI TEMPR1, C5
		RCALL PLAY_MUSICAL_NOTE
		RCALL JINGLE_BELLS_FOURTH_VERSE
		;	5th Verse
		RCALL JINGLE_BELLS_FIRST_VERSE
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		;	6th Verse
		RCALL JINGLE_BELLS_FIRST_VERSE
		LDI TEMPR1, D4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		;	7th Verse
		RCALL JINGLE_BELLS_THIRD_VERSE
		LDI TEMPR1, C5
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, C5
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, C5
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, C5
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3
		;	8th Verse
		LDI TEMPR1, D5
		RCALL PLAY_MUSICAL_NOTE
		RCALL JINGLE_BELLS_FOURTH_VERSE
		; Refrain, Twice
		RCALL JINGLE_BELLS_REFRAIN
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 2
		LDI TEMPR1, C5
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 2
		RCALL JINGLE_BELLS_REFRAIN
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 2
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 2
		RET;	SubProgram Return

	;*** Jingle Bells 1st Verse ***
	JINGLE_BELLS_FIRST_VERSE:
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3		
		RET;	SubProgram Return

	;*** Jingle Bells 2nd Verse ***
	JINGLE_BELLS_SECOND_VERSE:
		LDI TEMPR1, C4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3		
		RET;	SubProgram Return

	;*** Jingle Bells 3rd Verse ***
	JINGLE_BELLS_THIRD_VERSE:
		LDI TEMPR1, D4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, B4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3		
		RET;	SubProgram Return

	;*** Jingle Bells 4th Verse ***
	JINGLE_BELLS_FOURTH_VERSE:
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, C5
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, B4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 3
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 3		
		RET;	SubProgram Return

	;*** Jingle Bells Refrain ***
	JINGLE_BELLS_REFRAIN:
		LDI DELAY_PARAM, 2
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 2
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 2
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 2
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 2
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 2
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 2
		
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 2
		LDI TEMPR1, C5
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 2
		LDI TEMPR1, F4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 2
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 2
		
		LDI TEMPR2, 5
		JINGLE_BELLS_REFRAIN_LOOP1:
			LDI TEMPR1, B4
			RCALL PLAY_MUSICAL_NOTE
			LDI DELAY_PARAM, 1
			RCALL DELAY
			LDI DELAY_PARAM, 2
			DEC TEMPR2
			BRNE JINGLE_BELLS_REFRAIN_LOOP1
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 2
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 2
			
		LDI TEMPR2, 3
		JINGLE_BELLS_REFRAIN_LOOP2:
			LDI TEMPR1, A4
			RCALL PLAY_MUSICAL_NOTE
			LDI DELAY_PARAM, 1
			RCALL DELAY
			LDI DELAY_PARAM, 2
			DEC TEMPR2
			BRNE JINGLE_BELLS_REFRAIN_LOOP2
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 2
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 2
		LDI TEMPR1, A4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 1
		RCALL DELAY
		LDI DELAY_PARAM, 2
		LDI TEMPR1, G4
		RCALL PLAY_MUSICAL_NOTE
		LDI DELAY_PARAM, 2
		RCALL DELAY
		LDI DELAY_PARAM, 2				
		RET;	SubProgram Return


;****** Interrupt Routines ******

	;*** Timer 0 Overflow Interrupt Request Handler ***
	TIM0_OVF:
		DEC TEMPR1
		RETI;	Interrupt Return
